### ISSUE TITLE
Messages are lost due to bulk queue size

### ISSUE THREAD

**Issue by tsouza** [elastic/elasticsearch-river-rabbitmq#57]
Hello,

It seems that when BulkIndexRequest has failures (i.e. rejected due to bulk queue full), despite nack_errors set true, the river will ack the messages. Shouldn't it be nacked?

Looking through the source code, there a TODO suggesting that the message should be written to an exception queue. I disagree, IMO message should be rejected and/or requeued as per configuration.

Regards

**Comment by dadoonet** [comment]
This project is not maintained anymore.
