### ISSUE TITLE
Support for aliases

### ISSUE THREAD

**Issue by plcstevens** [elastic/elasticsearch-river-rabbitmq#69]
We currently use the RabbitMQ river to re-import/update/index large quantities of data each day. Due to how we are discovering this data we are able to update existing documents and index new ones, but we cannot remove/detect old documents which we have deleted.

One suggestion here is to use aliases for our index and each day create a new index and point our alias at that. We are not sure that this river currently supports this out of the box and so have been attempting it by altering the river settings to reflect the new day and then importing into that new index. Once enough time has passed, we send a command to switch the alias.

Is there any way to have this river support date-time indexes and/or aliasing?

**Comment by dadoonet** [comment]
Thanks for opening this!

But we won't support new features as rivers are now [deprecated](https://www.elastic.co/blog/deprecating_rivers).

Logstash might support better this out of the box (index per period).
