### ISSUE TITLE
Bulk Script - body passed as string encoding

### ISSUE THREAD

**Issue by georgiopandarez** [elastic/elasticsearch-river-rabbitmq#72]
AMQP is returning a byte array, and the bulk script is converting that to a string. The issue is that the default string encoding ruin's binary data - ie compressed streams.

The script interface should just deal with byte arrays (both as the return type and body parameter), as that is what AMQP is returning, this will let the script do what it wants with the raw data, rather then converting it posibally incorrectly before calling the script.

**Comment by dadoonet** [comment]
This project is not maintained anymore.
