### ISSUE TITLE
Queue processing does not resume after data node errors

### ISSUE THREAD

**Issue by hjz** [elastic/elasticsearch-river-rabbitmq#77]
We have a 3 master, 3 data node setup with 2 replicas, so all every node has all the data.

We had a case where the data node ran out of memory and was not responding to requests which backed up RabbitMQ.

We recovered by restarting all the data notes. Once recovered, the river didn't continue to process. The consumer was still connected.

Solution was to delete the river and recreate.

**Comment by dadoonet** [comment]
This project is not maintained anymore.
