### ISSUE TITLE
No data was indexed into elasticsearch

### ISSUE THREAD

**Issue by OElesin** [elastic/elasticsearch-river-rabbitmq#90]
After following the README, I observed that no data was indexed from RabbitMQ into ElasticSearch. 
What could be wrong?

{
    "took": 10,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "successful": 1,
        "failed": 0
    },
    "hits": {
        "total": 4,
        "max_score": 1,
        "hits": [
            {
                "_index": "_river",
                "_type": "my_river",
                "_id": "_status",
                "_score": 1,
                "_source": {
                    "error": "NoClassSettingsException[Failed to load class with value [rabbitmq]]; nested: ClassNotFoundException[rabbitmq]; ",
                    "node": {
                        "id": "RUS8EYFgRraiLU1EefhucA",
                        "name": "Captain UK",
                        "transport_address": "inet[/192.168.1.139:9300]"
                    }
                }
            }

**Comment by dadoonet** [comment]
You did not install the plugin or did not restart nodes.
